version: '3.1'

networks:
  hiperion-network:
    external: true

services:
  planner:
    image: kafka-topics-utils:1.0-RELEASE
    ports:
      - 9990:8080
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9093,kafka3:9094
      - SPACIFIC_CONSUMER_GROUP=CmsGroupId
